### ISSUE TITLE
Create tuple of tuples.

### ISSUE THREAD

**Issue by letoss** [joke2k/django-environ#47] opened 2015-10-01 19:40 UTC
Is there a way to create a tuple of tuples?
Example: (('user1', 'user1@mail.com'), ('user2', 'user2@mail.com'), )

I have the same problem trying to create a list of dicts.

**Comment by rmartins90** [comment] 2015-11-12 16:45
+1

**Comment by tiagofmc** [comment] 2015-11-23 11:07
+1

**Comment by joke2k** [comment] 2015-12-25 17:57
No, but you can use the json parser insted.
The problem is on these lines https://github.com/joke2k/django-environ/blob/develop/environ/environ.py#L289

**Comment by hernantz** [comment] 2016-11-03 14:43
@letoss for that particular example, you could use https://docs.python.org/2/library/email.util.html#email.utils.parseaddr to parse a single tuple of email addresses as strings. I.e: `('John Jones <john@jones.com>', 'foo <bar@baz.com>')`

**Comment by sandino** [comment] 2019-02-08 11:23
+1

@hernantz Django has [settings that consume list of tuples, such as ADMINS or MANAGERS](https://docs.djangoproject.com/en/2.2/ref/settings/#admins):

```
[('John', 'john@example.com'), ('Mary', 'mary@example.com')]
```
it would be nice not to hardcode them and fetch from environment.

**Comment by hernantz** [comment] 2019-02-08 15:07
@sandino You can accomplish that with 
```python
>>> from email.utils import parseaddr
>>> MANAGERS = '"First Last" <example@mail.com>, "Foo Bar" <foo@bar.com>' # or get it from the env
>>> tuple(parseaddr(email) for email in MANAGERS.split(','))
(('First Last', 'example@mail.com'), ('Foo Bar', 'foo@bar.com'))
```

**Comment by sandino** [comment] 2019-02-08 15:19
@hernantz This solves the problem, thanks!

**Comment by sergeyklay** [comment] 2021-09-01 18:12
The comment https://github.com/joke2k/django-environ/issues/47#issuecomment-167254176  explains how to get tuple of tuples. And the comment https://github.com/joke2k/django-environ/issues/47#issuecomment-461832572 demonstrates how to get list of tuples, such as ADMINS or MANAGERS. Closing this.

**Closed by sergeyklay** 2021-09-01 18:12 UTC
Labels: enhancement
