### ISSUE TITLE
'CACHE_URL' default value is not found using env.cache()

### ISSUE THREAD

**Issue by normoes** [joke2k/django-environ#186] opened 2018-06-22 07:23 UTC
Hi,

The environment:
**django-environ==0.4.4**
**Django==2.0.6**

I have **no** `CACHE_URL` environment variable set in the system.

In **settings.py** I use:
```
env = environ.Env(
    DEBUG=(bool, False),
    CACHE_URL=(str, "locmemcache://"),
)
```

On  calling `env.cache()` I expect to get a dictinoary like this:
`{'BACKEND': 'django.core.cache.backends.locmem.LocMemCache', 'LOCATION': ''}`

Instead I get:
```
raise KeyError(key) from None
KeyError: 'CACHE_URL'
```

`print(env('CACHE_URL'))` shows the correct default value.
`print(os.environ['CACHE_URL'])` raises a `KeyError`.

---

In the python shell the above workflow works perfectly - `env.cache()` returns what is expected.

---

Am I missing something?

Thanks,
Norman

**Comment by mehdy** [comment] 2021-10-05 10:33
@sergeyklay Would you mind if I work on this?

**Comment by sergeyklay** [comment] 2021-10-05 10:46
@mehdy This is still in my plans, I'm sorry, a bit busy at work these days. I'll try to sort out ASAP.

**Comment by mehdy** [comment] 2021-10-05 10:55
@sergeyklay Actually, I was hoping you'd let me contribute :P

**Comment by sergeyklay** [comment] 2021-10-05 11:16
@mehdy Ah, PRs are always welcome!

**Comment by mehdy** [comment] 2021-10-05 14:09
@sergeyklay I tried to reprodue the issue but I couldn't. You may close the issue.

**Comment by sergeyklay** [comment] 2021-10-05 16:28
Could you plese send a test?

**Comment by mehdy** [comment] 2021-10-05 18:33
@sergeyklay Sure!

**Closed** 2021-10-06 08:16 UTC
Labels: bug

**Comment by sergeyklay** [comment] 2021-10-06 08:17
I'm closing since this is a not a bug, but if I have made an oversight, please do get back in touch. Thanks.
