### ISSUE TITLE
Using '$' inside .env file does not work 

### ISSUE THREAD

**Issue by vubon** [joke2k/django-environ#213] opened 2019-02-03 08:20 UTC
When using first character as $ . It raise Improperly Configured 
Example: 
Inside .env file 

USER_TEST=$123bnsfbndsbf

Settings.py 
envfile_path = os.path.join(BASE_DIR, '.env')
environ.Env.read_env(envfile_path)

TEST = env("USER_TEST")

After all I checked here is the problem to get $ symbol value 
[Code Line number](https://github.com/joke2k/django-environ/blob/b32c07d7ed57cdeaef246f995a29e5fe39a076b3/environ/environ.py#L282)

Can anybody explain me please? Why do we need to resolve any proxied values ?? Thanks

**Comment by Jafnee** [comment] 2019-02-07 06:21
Looks like it's to allow using another environment variable as the value

**Comment by Xzya** [comment] 2019-03-05 09:48
Any solution to this? How can we use values that start with `$`?

**Comment by vubon** [comment] 2019-03-05 10:51
> Any solution to this? How can we use values that start with `$`?

You may override the condition. 
Condition line number: https://github.com/joke2k/django-environ/blob/b32c07d7ed57cdeaef246f995a29e5fe39a076b3/environ/environ.py#L282

**Comment by juanortizoviedo** [comment] 2020-04-04 19:56
@vubon not working !!!
my SECRET_KEY=$%=%6asjj77sHFa...
an error ocurred in line 273 

Traceback (most recent call last):
  File "/home/user/.cache/pypoetry/virtualenvs/backend--UdpC4sg-py3.6/lib/python3.6/site-packages/environ/environ.py", line 273, in get_value
    value = self.ENVIRON[var]
  File "/usr/lib/python3.6/os.py", line 669, in __getitem__
    raise KeyError(key) from None
KeyError: '6asjj77sHFa...'

but if I remove "$" work fine.

Please help me, thanks in advance !

**Comment by fdemmer** [comment] 2021-01-28 19:41
duplicate of long standing issue #60

**Closed** 2021-09-05 00:35 UTC
Labels: duplicate
