### ISSUE TITLE
RecursionError when default value starts with a "$"

### ISSUE THREAD

**Issue by AllexVeldman** [joke2k/django-environ#285] opened 2021-01-14 13:01 UTC
A RecursionError is raised when the default of a str value is set to a string starting with `$`

```python
ENV = environ.Env(
    FOO=(str, "$bar")

ENV("FOO") # -> Raises RecursionError
```

```
  File "/.tox/py39/lib/python3.9/site-packages/environ/environ.py", line 123, in __call__
    return self.get_value(var, cast=cast, default=default, parse_default=parse_default)
  File "/.tox/py39/lib/python3.9/site-packages/environ/environ.py", line 284, in get_value
    value = self.get_value(value, cast=cast, default=default)
  File "/.tox/py39/lib/python3.9/site-packages/environ/environ.py", line 284, in get_value
    value = self.get_value(value, cast=cast, default=default)
  File "/.tox/py39/lib/python3.9/site-packages/environ/environ.py", line 284, in get_value
    value = self.get_value(value, cast=cast, default=default)
  [Previous line repeated 951 more times]
  File "/.tox/py39/lib/python3.9/site-packages/environ/environ.py", line 247, in get_value
    logger.debug("get '{0}' casted as '{1}' with default '{2}'".format(
RecursionError: maximum recursion depth exceeded while getting the str of an object
```

There is a small chance this happens when using `get_random_secret_key()` as the default.

```
Django                3.1.5
django-environ        0.4.5
```

Related-to #284

**Comment by fdemmer** [comment] 2021-01-28 19:42
duplicate of long standing issue #60

**Closed** 2021-02-01 08:07 UTC
