### ISSUE TITLE
django-envrion env.db doesn't work with manage.py inspectdb

### ISSUE THREAD

**Issue by thaxy** [joke2k/django-environ#147] opened 2017-10-06 08:31 UTC
Given the following ``DATABASES`` variable in my ``config.py``:
```
DATABASES = {
    'default': env.db('DATABASE_URL', default='postgres:///server'),
}
DATABASES['default']['ATOMIC_REQUESTS'] = True
print(DATABASES)
```
Results as expected when I run my server to:
`{'default': {'NAME': 'postgres', 'PORT': 5432, 'ENGINE': 'django.db.backends.postgresql_psycopg2', 'USER': 'postgres', 'ATOMIC_REQUESTS': True, 'PASSWORD': '', 'HOST': 'postgres'}}`

But when executing the ``manage.py inspectdb`` command (which loads the same ``config.py`` file) results in:
`{'default': {'ENGINE': 'django.db.backends.postgresql_psycopg2', 'ATOMIC_REQUESTS': True, 'PORT': '', 'USER': '', 'PASSWORD': '', 'NAME': 'server', 'HOST': ''}}`

**Comment by sergeyklay** [comment] 2022-06-14 22:22
I'm closing this issue since this is very old report and I was unable to reproduce described issue, but if I have made an oversight, please do get back in touch.  Thanks.

**Closed by sergeyklay** 2022-06-14 22:22 UTC
Labels: bug
