### ISSUE TITLE
Improperly Configured Error

### ISSUE THREAD

**Issue by CyberReverend** [joke2k/django-environ#273] opened 2020-08-26 02:23 UTC
I am receiving the following error when running handsontable_tools.py:

```
root@crits:/data/crits/crits/core# python handsontable_tools.py
Traceback (most recent call last):
  File "handsontable_tools.py", line 7, in <module>
    from data_tools import convert_string_to_bool, remove_html_tags
  File "/data/crits/crits/core/data_tools.py", line 19, in <module>
    from mongo_tools import get_file
  File "/data/crits/crits/core/mongo_tools.py", line 2, in <module>
    if settings.FILE_DB == settings.S3:
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 39, in _setup
    % (desc, ENVIRONMENT_VARIABLE))
django.core.exceptions.ImproperlyConfigured: Requested setting FILE_DB, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.
```

Any assistance would be greatly appreciated!

**Comment by sur0g** [comment] 2020-11-24 13:25
It's not a django-environ problem.
The problem here lies in `/data/crits/crits/core/mongo_tools.py(2)`. There's an import statement that tries to import django settings, which are not configured yet (see the last traceback line).

There's no any configured django instances when you run a file from shell just like that.
You have to set up django settings first. See official django docs for details [here](https://docs.djangoproject.com/en/stable/topics/settings/#designating-the-settings).

**Comment by sergeyklay** [comment] 2021-09-04 16:41
I'm closing since this is a not a bug report. Please check the mentioned solution. If you are still experiencing this and have some more additional info feel free open a new issue.

**Closed by sergeyklay** 2021-09-04 16:41 UTC
