### ISSUE TITLE
Casting for tuples

### ISSUE THREAD

**Issue by zyzzyxdonta** [joke2k/django-environ#387] opened 2022-05-02 07:39 UTC
I think there is something wrong with casting tuples to the right types. Here is an example:

```bash
TEST_ENV="(0,Test)" python -c 'import environ; env = environ.Env(); print(env.tuple("TEST_ENV", default=(0, "")))'
```

This returns `('0', 'Test')`, i.e. a tuple of strings.

I tried casting it with a lambda which should be possible according to #54:

```bash
TEST_ENV="(0,Test)" python -c 'import environ; env = environ.Env(); print(env.tuple("TEST_ENV", default=(0, ""), cast=lambda t: (int(t[0]), t[1])))'
```

But this returns an error:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/.../.cache/pypoetry/virtualenvs/...-py3.10/lib/python3.10/site-packages/environ/environ.py", line 249, in tuple
    return self.get_value(
  File "/home/.../.cache/pypoetry/virtualenvs/...-py3.10/lib/python3.10/site-packages/environ/environ.py", line 394, in get_value
    value = self.parse_value(value, cast)
  File "/home/.../.cache/pypoetry/virtualenvs/...-py3.10/lib/python3.10/site-packages/environ/environ.py", line 420, in parse_value
    value = tuple(map(cast[0], [x for x in val if x]))
  File "<string>", line 1, in <lambda>
IndexError: string index out of range
```

Is there a way to do this without accepting the string and casting it to int myself?

**Comment by sergeyklay** [comment] 2022-06-14 01:16
This is not entirely a bug and unfortunately at this stage it is not so easy to simplify the workaround but there is a working example:

```pycon
$ TEST_ENV="(0,Test)" python
Python 3.10.5 (main, Jun 13 2022, 12:27:37) [Clang 13.1.6 (clang-1316.0.21.2.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import environ
>>> env = environ.Env()
>>> caster = lambda v: int(v) if v.isdigit() else v.strip()
>>> env("TEST_ENV", default=(0, ""), cast=lambda t: tuple(map(caster, [c for c in t.strip('()').split(',')])))
(0, 'Test')
>>>
```

The issue is that after you define a function to cast:

```python
cast=lambda t: (int(t[0]), t[1]))
```

Lambda get untouched string:

https://github.com/joke2k/django-environ/blob/bdc48f5abe2fd4370b5d0988bb8dd2feb7afc0d1/environ/environ.py#L457-L458

We can't parse `value` before because we actually don't know the purpose of the lambda.
Thus, in your lambda expression `t` is `'(0,Test)'` and `t[0]` is `'('`.

Unfortunately, current parsing algorithms don't allow to get what you want in a more concise way. I whant to close this issue because I don't want a bunch of these lying around. I'd like to add support for anything/everything at some point, but keeping the issue open doesn't help that. :) If anyone wants to get started, I'd love that.

**Comment by sergeyklay** [comment] 2022-06-14 20:44
I don't know how this will help you, but here are some more ideas. It remains only to implement something like `quote_nonnumeric(x)` to make `'(42, "Test")'` from `'(42, Test)'`:


Using [ast.literal_eval()](http://docs.python.org/library/ast.html#ast.literal_eval):
```pycon
In [1]: from ast import literal_eval

In [2]: literal_eval('(1,2,3,4,5),(5,4,3,2,1)')
Out[3]: ((1, 2, 3, 4, 5), (5, 4, 3, 2, 1))

In [4]: literal_eval('(42, "Test")')
Out[5]: (42, 'Test')
```

The shortest one:
```pycon
In [1]: eval('(42, "Test")')
Out[1]: (42, 'Test')

In [2]: eval('(1,2,3,4,5),(5,4,3,2,1)')
Out[2]: ((1, 2, 3, 4, 5), (5, 4, 3, 2, 1))
```

**Closed by sergeyklay** 2022-06-14 20:44 UTC
Labels: help wanted
