### ISSUE TITLE
Using `#` in a database_url considered as a comment and while parsing it does not even show any warning/error

### ISSUE THREAD

**Issue by reyadussalahin** [joke2k/django-environ#288] opened 2021-03-07 15:56 UTC
I've tried the followings for `django-environ==0.4.5`

First case, using `.db_url_config()`
```python
>>> import environ
>>> env = environ.Env()
>>> env.db_url_config("postgres://user:123#abc@host:1234/dbname")
{'NAME': '', 'USER': '', 'PASSWORD': '', 'HOST': 'user', 'PORT': 123, 'ENGINE': 'django.db.backends.postgresql'}
```

Then, using a `.env` file loading using `.read_env()` with same `DATABASE_URL`.
```python
>>> import environ
>>> env = environ.Env()
>>> env.read_env(".env")
>>> env.db()
{'NAME': '', 'USER': '', 'PASSWORD': '', 'HOST': 'user', 'PORT': 123, 'ENGINE': 'django.db.backends.postgresql'}
```

The problem here is that `django-environ` does not show any warning or error if it receives such values that it can't parse or parse in a wrong manner. It just results in a time wasting debugging for someone who is not aware of such situation.

A warning or error would be a nice addition for such cases.

**Comment by 1oglop1** [comment] 2021-07-14 04:55
@reyadussalahin I think this is a dupe of #298

**Comment by sergeyklay** [comment] 2021-08-30 13:00
Internally django-environ uses `urllib` to parse URL-like schemas. In turn, `urllib` follows [RFC 3986](https://datatracker.ietf.org/doc/html/rfc3986) to parse URIs. Therefore, you should encode all unsafe characters in the  userinfo part to achieve the expected behavior from django-environ.


Consider the following **wrong** example:

```shell
   # .env file contents
   DATABASE_URL='postgres://user:#@host:5432/db'
```

```py
   # settings.py file contents
   import environ


   env = environ.Env()
   result = env.db('DATABASE_URL')

   assert result['NAME'] == ''
   assert result['USER'] == ''
   assert result['PASSWORD'] == ''
   assert result['HOST'] == 'user'
   assert result['PORT'] == ''
   assert result['ENGINE'] == 'django.db.backends.postgresql'
```

Here, the number sign (`#`) was passed as unencoded, raw value.  However,
according to [RFC 3986 #2.2](https://datatracker.ietf.org/doc/html/rfc3986#section-2.2) the number sign character must be encoded:


>    URIs include components and subcomponents that are delimited by
>    characters in the "reserved" set.  These characters are called
>    "reserved" because they may (or may not) be defined as delimiters by
>    the generic syntax, by each scheme-specific syntax, or by the
>    implementation-specific syntax of a URI's dereferencing algorithm.
>    If data for a URI component would conflict with a reserved
>    character's purpose as a delimiter, then the conflicting data must be
>    percent-encoded before the URI is formed.
> 
>    reserved    = gen-delims / sub-delims
> 
>    gen-delims  = ":" / "/" / "?" / "#" / "[" / "]" / "@"
> 
>    sub-delims  = "!" / "$" / "&" / "'" / "(" / ")"
>                / "*" / "+" / "," / ";" / "="

Thus, to make this example valid, we have to fix it as follows:

```shell
   # .env file contents
   DATABASE_URL='postgres://user:%23@host:5432/db'
```

```py
   # settings.py file contents
   import environ

   env = environ.Env()
   result = env.db('DATABASE_URL')

   assert result['NAME'] == 'db'
   assert result['USER'] == 'user'
   assert result['PASSWORD'] == '#'
   assert result['HOST'] == 'host'
   assert result['PORT'] == 5432
   assert result['ENGINE'] == 'django.db.backends.postgresql'
```

See https://perishablepress.com/stop-using-unsafe-characters-in-urls/ for reference.

**Closed by sergeyklay** 2021-08-30 13:00 UTC
