### ISSUE TITLE
When loading .env in windows, the Envrion is not populated

### ISSUE THREAD

**Issue by gone** [joke2k/django-environ#253] opened 2020-03-19 15:34 UTC
Same script running fine in linux/mac, when running on windows we need to use another project such as python-dotenv to get the .env loaded. Access loaded environment variables works fine though.

**Comment by sergeyklay** [comment] 2021-08-31 22:31
@gone Could you please provide the minimal code to reproduce?

**Comment by Xoma163** [comment] 2021-09-19 04:56
> @gone Could you please provide the minimal code to reproduce?

```
import environ
env = environ.Env()
env.read_env(os.path.join(BASE_DIR, 'secrets/.env'))
```

```
Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "C:\Users\Xoma163\PycharmProjects\petrovich\venv\lib\site-packages\django\core\management\__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "C:\Users\Xoma163\PycharmProjects\petrovich\venv\lib\site-packages\django\core\management\__init__.py", line 363, in execute
    settings.INSTALLED_APPS
  File "C:\Users\Xoma163\PycharmProjects\petrovich\venv\lib\site-packages\django\conf\__init__.py", line 82, in __getattr__
    self._setup(name)
  File "C:\Users\Xoma163\PycharmProjects\petrovich\venv\lib\site-packages\django\conf\__init__.py", line 69, in _setup
    self._wrapped = Settings(settings_module)
  File "C:\Users\Xoma163\PycharmProjects\petrovich\venv\lib\site-packages\django\conf\__init__.py", line 170, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "C:\Users\Xoma163\AppData\Local\Programs\Python\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Xoma163\PycharmProjects\petrovich\petrovich\settings.py", line 10, in <module>
    env.read_env(os.path.join(BASE_DIR, 'secrets/.env'))
  File "C:\Users\Xoma163\PycharmProjects\petrovich\venv\lib\site-packages\environ\environ.py", line 760, in read_env
    content = f.read()
  File "C:\Users\Xoma163\AppData\Local\Programs\Python\Python38\lib\encodings\cp1251.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 647: character maps to <undefined>

Process finished with exit code 1
```

**Comment by sergeyklay** [comment] 2021-10-06 18:59
I'm closing this issue due to the lack of any reaction. I'll open it again if the need arises

**Closed by sergeyklay** 2021-10-06 18:59 UTC
Labels: need script to reproduce
